export const images = {
  HomeDecore: require('../res/images/ExploreScreen/HomeDecore.png'),
  AhemdabadOneMall: require('../res/images/ExploreScreen/AhemdabadOneMall.png'),
  Accessories: require('../res/images/ExploreScreen/Accessories.png'),
  bags: require('../res/images/ExploreScreen/bags.png'),
  DepartmentStore: require('../res/images/ExploreScreen/DepartmentStore.png'),
  Spas: require('../res/images/ExploreScreen/Spas.png'),
  SportsShoes: require('../res/images/ExploreScreen/SportsShoes.png'),
  WestendMall: require('../res/images/ExploreScreen/WestendMall.png'),
  eyecare: require('../res/images/Eyewear.png'),
  logo: require('../res/images/logo.jpg'),
  Share: require('../res/images/Share.png'),
  Approve: require('../res/images/Approve.png'),
  Checkbox: require('../res/images/Checkbox.png'),
  Checkbox_Blank: require('../res/images/Checkbox_Blank.png'),
  Add_1: require('../res/images/Add_1.png'),
  ScanCode: require('../res/images/ScanCode.png'),
  DropDownarrow: require('../res/images/DropDownarrow.png'),
  Delete: require('../res/images/Delete.png'),
  Home_screen_Like: require('../res/images/Home_screen_Like.png'),
  Star_Rating_Inactive: require('../res/images/Star_Rating_Inactive.png'),
  SGC_Notification: require('../res/images/SGC_Notification.png'),
  Filter: require('../res/images/Filter.png'),
  Loyalty_Rewards: require('../res/images/LoyaltyRewardPoints.png'),
  Shopping: require('../res/images/Shopping.png'),
  Checkin: require('../res/images/Check-in.png'),
  Bill: require('../res/images/UploadBill.png'),
  BIBA: require('../res/images/BIBA-logo.png'),
  Camera: require('../res/images/Camera.png'),
  UPI: require('../res/images/UPI.png'),
  OnlineStream: require('../res/images/OnlineStreaming.png'),
  RightArrow: require('../res/images/RightArrow.png'),
  NetBanking: require('../res/images/NetBanking.png'),
  DebitCard: require('../res/images/DebitCard.png'),
  SilverBadge: require('../res/images/SilverBadge.png'),
  Translate: require('../res/images/Translate.png'),
  TanishqLogo: require('../res/images/TanishqLogo.png'),
  BeingHuman: require('../res/images/BeingHuman.png'),
  BIBA_logo: require('../res/images/BIBA-logo.png'),
  Sports_Shoes: require('../res/images/Sports-Shoes.png'),
  Close: require('../res/images/Close.png'),
  GOOGLE_MAPS: require('../res/images/GOOGLE_MAPS.png'),
  Navigate: require('../res/images/Navigate.png'),
  ParkingView: require('../res/images/ParkingView.png'),
  Up_Arrow: require('../res/images/Up_Arrow.png'),
  NorthMap: require('../res/images/NorthMap.png'),
  visa: require('../res/images/visa.png'),

  ShoppersStop: require('../res/images/ShoppersStop.png'),
  OKEN_Logo_Icon: require('../res/images/splashScreen/OKEN_Logo_Icon.png'),
  OKEN_Logo_Text: require('../res/images/splashScreen/OKEN_Logo_Text.png'),

  OKEN_Logo: require('./images/autoService/OKEN_Logo.png'),

  Avatar: require('./images/autoService/Avatar.png'),
  Password: require('./images/autoService/Password_Lock.png'),

  Facebook_Active: require('./images/autoService/Facebook_Active.png'),
  Google_Active: require('./images/autoService/Google_Active.png'),
  Instagram_Active: require('./images/autoService/Instagram_Active.png'),
  Twitter_Active: require('./images/autoService/Twitter_Active.png'),

  Twitter_Inactive: require('./images/autoService/Twitter_Inactive.png'),
  Instagram_Inactive: require('./images/autoService/Instagram_Inactive.png'),
  Google_Inactive: require('./images/autoService/Google_Inactive.png'),
  Facebook_Inactive: require('./images/autoService/Facebook_Inactive.png'),
  Email: require('./images/autoService/Email.png'),

  Mobile: require('./images/autoService/Mobile.png'),
  Right_Tick: require('./images/autoService/Right_Tick.png'),

  TargetLocation: require('./images/autoService/TargetLocation.png'),
  Search: require('./images/autoService/Search.png'),

  Events_Inactive: require('./images/bottomTab/Events_Inactive.png'),
  Explore_Inactive: require('./images/bottomTab/Explore_Inactive.png'),
  Home_Inactive: require('./images/bottomTab/Home_Inactive.png'),
  Map_Inactive: require('./images/bottomTab/Map_Inactive.png'),
  OKEN_Inactive: require('./images/bottomTab/OKEN_Inactive.png'),
  QRCode_Inactive: require('./images/bottomTab/QRCode_Inactive.png'),
  Menu: require('./images/bottomTab/Menu.png'),

  ShoppingList: require('./images/drawerImages/ShoppingList.png'),
  UploadedBills: require('./images/drawerImages/UploadedBills.png'),
  Back: require('./images/drawerImages/back.png'),
  Refer_a_Friend: require('./images/drawerImages/Refer_a_Friend.png'),
  RateUs: require('./images/drawerImages/RateUs.png'),
  HelpCenter: require('./images/drawerImages/HelpCenter.png'),
  Feedback_Survey: require('./images/drawerImages/Feedback_Survey.png'),
  Settings: require('./images/drawerImages/Settings.png'),
  TermsConditions: require('./images/drawerImages/TermsConditions.png'),
  FAQs: require('./images/drawerImages/FAQs.png'),
  Logout: require('./images/drawerImages/Logout.png'),

  UserAvatar: require('./images/UserAvatar.png'),
  NotificationBell_ON: require('./images/NotificationBell_ON.png'),

  Home_screen_image: require('../res/images/Home/Home-screen_image.png'),
  SGC_Mall_image: require('../res/images/Home/SGC-Mall-image.png'),
  Directions: require('../res/images/Home/Directions.png'),
  Favorite_Heart: require('../res/images/Home/Favorite_Heart.png'),
  Location: require('../res/images/Home/Location.png'),
  Star: require('../res/images/Home/Star.png'),
  Loyalty_Background: require('../res/images/Home/Loyalty_Background-1.png'),
  Coin_Money: require('../res/images/Home/Coin_Money.png'),
  SGC_Events: require('../res/images/Home/SGC_Events.png'),
  AhemdabadOneMallEvents: require('../res/images/Home/Ahemdabad-One-Mall_Events.png'),
  EMallElantevents: require('../res/images/Home/Elante-Mall_Events.png'),
  Spin_Win: require('../res/images/Home/Spin-&-Win.png'),
  Westend_Mall: require('../res/images/Home/Westend-Mall.png'),

  SGC_Mall_Explore: require('../res/images/MallDetails/SGC_Mall_Explore.png'),
  Contact: require('../res/images/MallDetails/Contact.png'),
  SmartParking: require('../res/images/MallDetails/SmartParking.png'),
  SocialFeeds: require('../res/images/MallDetails/SocialFeeds.png'),
  UploadBill: require('../res/images/MallDetails/UploadBill.png'),
  MyVouchers: require('../res/images/MallDetails/MyVouchers.png'),
  MensWear: require('../res/images/MallDetails/Men’sWear.png'),
  BeautyCareandProducts: require('../res/images/MallDetails/BeautyCareandProducts.png'),
  EntertainmentandFun: require('../res/images/MallDetails/EntertainmentandFun.png'),
  HomeDecor: require('../res/images/MallDetails/HomeDecor.png'),
  KidsWear: require('../res/images/MallDetails/KidsWear.png'),
  WomansWear: require('../res/images/MallDetails/Woman’sWear.png'),
  Timings: require('../res/images/MallDetails/Timings.png'),
  Westend_Mall_Events: require('../res/images/MallDetails/Westend_Mall_Events.png'),
  Multiplex: require('../res/images/MallDetails/Multiplex.png'),
  Fashion: require('../res/images/MallDetails/Fashion.png'),
  Reviews: require('../res/images/MallDetails/Reviews.png'),
  info: require('../res/images/MallDetails/info.png'),
  Car: require('../res/images/MallDetails/SmartParking1.png'),
  CarMap: require('../res/images/MallDetails/SmartParking2.png'),
  refresh: require('../res/images/MallDetails/refresh.png'),
  BottomArrow: require('../res/images/bottomArrow.png'),
  Calender: require('../res/images/Calendar_1.png'),

  Arrow: require('../res/images/Arrow.png'),
  Music: require('../res/images/Music.png'),
  Clock: require('../res/images/Clock.png'),

  Uploaded_Bills_History_Bill: require('../res/images/Uploaded-Bills-History-Bill.png'),
  Uploaded_Bills_History_Bill_2: require('../res/images/Uploaded-Bills-History-Bill_2.png'),
};
