import {StyleSheet} from 'react-native';
import scale from '../utils/Scale';
import R from '../R';
import React from 'react';

export default StyleSheet.create({
  Home_screen_image: {
    height: scale(140),
    width: scale(375),
    marginTop: scale(10),
  },
  container: {
    flexDirection: 'row',
    //justifyContent: 'space-around',
    marginLeft: scale(5),
    marginTop: scale(15),
  },
  customTxtStyle: {
    fontSize: scale(12),
    color: R.colors.white,
    opacity: scale(1),
  },
  customStyle: {
    alignSelf: 'center',
    width: scale(95),
    marginLeft: scale(15),
    height: scale(25),
    borderRadius: scale(1),
  },
  text: {
    fontSize: scale(10),
    alignSelf: 'center',
    color: R.colors.coolGrey,
  },
  title: {
    fontSize: scale(16),
    fontWeight: 'bold',
    marginTop: scale(20),
    // marginLeft: scale(15),
    color: R.colors.black,
  },
  customButtonTxtStyle: {
    fontSize: scale(12),
    color: R.colors.white,
    opacity: scale(1),
  },
  customButtonStyle: {
    marginLeft: scale(110),
    backgroundColor: R.colors.voilet,
    alignSelf: 'center',
    width: scale(70),
    height: scale(25),
    marginTop: scale(15),
  },
  shareImage: {
    marginTop: scale(5),
    alignSelf: 'center',
    height: scale(22),
    width: scale(22),
  },
  productName: {
    fontSize: scale(12),
    alignSelf: 'center',
    color: R.colors.black,
  },
  productImage: {
    height: scale(60),
    width: scale(110),
    alignSelf: 'center',
  },
  productView: {
    backgroundColor: R.colors.white,
    borderRadius: scale(12),
    width: scale(110),
    height: scale(80),
  },
  hightlightView: {
    width: scale(60),
    height: scale(20),
    position: 'absolute',
    bottom: 0,
    borderTopRightRadius: scale(18),
  },
  hightlightText: {
    fontSize: scale(10),
    fontWeight: 'bold',
    alignSelf: 'center',
    marginLeft: scale(10),
    marginTop: scale(5),
    color: R.colors.white,
  },
  interestText: {
    fontSize: scale(12),
    fontWeight: 'bold',
    marginTop: scale(5),
    alignSelf: 'center',
    color: R.colors.black,
  },
  rewardView: {
    width: scale(210),
    height: scale(100),
    marginTop: scale(20),
    borderStyle: 'dotted',
    borderColor: R.colors.grey,
    borderWidth: scale(1),
    marginBottom: scale(40),
    backgroundColor: R.colors.white,
    borderRadius: scale(7),
  },
  rewardImage: {
    width: scale(65),
    height: scale(15),
    marginLeft: scale(10),
  },
  rewardName: {
    fontSize: scale(10),
    marginLeft: scale(5),
    color: R.colors.black,
  },
  leftTextView: {
    borderTopLeftRadius: scale(15),
    borderBottomLeftRadius: scale(15),
    backgroundColor: R.colors.deeppink,
    height: scale(15),
    width: scale(50),
    marginLeft: scale(10),
  },
  leftText: {
    color: R.colors.white,
    fontSize: scale(10),
    alignSelf: 'center',
  },
  expiresText: {
    fontSize: scale(7),
    marginLeft: scale(5),
    color: R.colors.coolGrey,
  },
  dateText: {
    fontSize: scale(9),
    marginLeft: scale(5),
    color: R.colors.black,
  },
  linearGradientView: {
    height: scale(20),
    width: scale(55),
    alignSelf: 'center',
    marginLeft: scale(55),
    flexDirection: 'row',
    borderRadius: scale(18),
  },
  coinImage: {
    marginLeft: scale(5),
    width: scale(14),
    height: scale(14),
    alignSelf: 'center',
  },
  bottomView: {
    position: 'absolute',
    bottom: 0,
    height: scale(150),
    width: '100%',
    backgroundColor: R.colors.white,
    borderTopLeftRadius: scale(30),
    borderTopRightRadius: scale(30),
  },
  shareTextView: {
    borderBottomColor: R.colors.coolGrey,
    borderBottomWidth: scale(0.3),
    paddingBottom: scale(5),
  },
  socialImageLogo: {
    height: scale(120),
    width: scale(100),
  },
});
