import {StyleSheet} from 'react-native';
import R from '../../R'
import scale from '../../utils/Scale';
export default StyleSheet.create({
  fourthView: {
    marginTop: scale(10),

    borderWidth: scale(1),
    height: scale(30),
    width: scale(50),
    justifyContent: 'center',
    borderColor: R.colors.lightgrey,
  },
  shareText: {
    color: R.colors.black,
    textAlign: 'center',
    fontSize: scale(11),
  },
  bText: {
    color: R.colors.black,
    textAlign: 'center',
    fontSize: scale(15),
    color: R.colors.white,
    fontWeight: 'bold',
  },
  fontView: {fontSize: scale(11)},
  bView: {
    backgroundColor: R.colors.blueviolet,
    borderWidth: scale(1),
    borderTopLeftRadius: scale(5),
    borderBottomLeftRadius: scale(5),
    height: scale(30),
    width: scale(30),
    justifyContent: 'center',
    borderRightColor: R.colors.blueviolet,
    borderRightWidth: 1,
    borderBottomColor: R.colors.blueviolet,
    borderTopColor: R.colors.blueviolet,
    borderLeftColor: R.colors.blueviolet,
  },
  bookView: {
    backgroundColor: R.colors.blueviolet,

    height: scale(40),
    width: scale(140),
    borderRadius: scale(25),
    marginLeft: scale(20),
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  cView: {
    backgroundColor: R.colors.blueviolet,
    borderWidth: scale(1),
    height: scale(30),
    width: scale(30),
    justifyContent: 'center',
    borderTopRightRadius: scale(5),
    borderBottomRightRadius: scale(5),
    borderTopColor: R.colors.blueviolet,
    opacity: 0.8,
    borderBottomColor: R.colors.blueviolet,
    borderRightColor: R.colors.blueviolet,
    borderLeftColor: R.colors.gainsboro,
  },
  upperView: {
    flexDirection: 'row',
    borderBottomColor: R.colors.black,
    borderWidth: 1,
    backgroundColor: R.colors.white,
  },
  imgView: {height: scale(25), width: scale(25), margin: scale(10)},
  textStyle: {
    marginTop: scale(10),
    marginLeft: scale(20),
    marginBottom: scale(10),
  },
  parkView: {
    backgroundColor: R.colors.ghostwhite,
    flexDirection: 'column',
  },
  parkImg: {
    height: scale(480),
    width: scale(350),
    marginTop: scale(10),
    alignSelf: 'center',
  },
  newView: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: R.colors.gainsboro,
  },
  latestV: {
    width: scale(60),
    height: scale(30),
    borderColor: R.colors.gainsboro,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    borderRadius: scale(5),
    borderWidth: 1,
    marginLeft: scale(20),
    backgroundColor: R.colors.blueviolet,
  },
  parktext: {color: R.colors.white, fontSize: scale(16)},
  lastV: {height: scale(35), width: scale(35), margin: scale(10)},
});
