import {StyleSheet,} from 'react-native';
import scale from '../../utils/Scale';
import R from '../../R'
export default StyleSheet.create({
  text1: {
    fontWeight: 'bold',
    fontSize: scale(20),
    textAlign: 'center',
  },
  text3: {
    color: R.colors.white,
    fontSize: scale(22),
    fontWeight: 'bold',
    justifyContent: 'center',
    textAlign: 'center',
    padding: scale(5),
  },
  text4: {
    fontSize: scale(16),
    color: R.colors.grey,
    textAlign: 'center',
    marginLeft: scale(50),
    marginRight: scale(40),
    padding: scale(15),
  },
  text5: {
    fontWeight: 'bold',
    fontSize: scale(16),
    textAlign: 'center',
    marginLeft: scale(50),
    marginRight: scale(50),
    padding: scale(10),
  },
  text2: {
    fontWeight: 'bold',
    padding: scale(10),
    fontSize: scale(18),
    marginBottom: scale(10),
    marginTop: scale(50),
    justifyContent: 'center',
    marginLeft: scale(30),
  },
  RectangleShapeView: {
    padding: scale(6),
    borderWidth: scale(1),
    alignContent: 'center',
    marginTop: scale(20),
    borderRadius: scale(40),
    borderColor: R.colors.slateblue,
    borderWidth: scale(4),
    //marginBottom:600,
    marginLeft: scale(50),
    marginRight: scale(50),
    height: scale(60),
    width: scale(60 * 5),
  },
  text6: {
    fontSize: scale(18),
    fontWeight: 'bold',
    justifyContent: 'center',
    textAlign: 'center',
  },
  RectangleShapeView1: {
    padding: scale(5),
    borderWidth: scale(1),
    alignContent: 'center',
    margin: scale(20),
    borderRadius: scale(40),
    borderColor: R.colors.aquablue,
    backgroundColor: R.colors.slateblue,
    marginLeft: scale(50),
    marginRight: scale(50),
    height: scale(60),
    width: scale(60 * 5),
  },
  submit: {
    padding: scale(5),
    borderWidth: scale(1),
    alignContent: 'center',
    margin: scale(20),
    borderRadius: scale(70),
    borderColor: R.colors.aquablue,
    backgroundColor: R.colors.snowred,
    marginLeft: scale(100),
    marginRight: scale(50),
    height: scale(40),
    width: scale(40 * 5),
    justifyContent: 'center',
  },
});
